### ISSUE TITLE
[BUG] Device mapping issue during `load_learnable`

### ISSUE THREAD

**Issue by Morphlng** [takuseno/d3rlpy#443]
# Describe the bug
Hi there! I'm new to d3rlpy and having a little trouble of using trained checkpoint for inference. I used the following line to load checkpoint as the document said:

```python
algo = d3rlpy.load_learnable(args.ckpt, device="cuda:0")
```

But as long as the device is not `cpu`, I'll always encounter an error saying "TypeError: device(): argument 'index' (position 2) must be int, not str". I believe this is due to the following lambda function:

https://github.com/takuseno/d3rlpy/blob/0e8097b5fa77fcb85350bd039242d8af0b87504c/d3rlpy/torch_utility.py#L88

`device` here is "cuda:0" but it is expecting 0 instead?

# To Reproduce
1. Train any algorithm offline, and save the final ckpt with `FileAdapterFactory`.
2. Use the following code to load the algorithm:

```python
import d3rlpy

algo = d3rlpy.load_learnable("path/to/d3_ckpt", device="cuda")
# According to the doc string, device should be fine when using: True, "cuda", "cuda:0", 0.
```

# Expected behavior
I'm expecting the code to successfully load the checkpoint on GPU.

# Additional context
1. d3rlpy version: 2.6.1
2. torch version: 2.5.1

**Comment by takuseno** [comment]
@Morphlng Hi, thank you for reporting this issue! I have fixed this error in the latest commit https://github.com/takuseno/d3rlpy/commit/baef437d964879980c76fbe3985fc14ebe29cd2b . If you install d3rlpy from source code, the issue should be resolved.

**Comment by takuseno** [comment]
Please let m .close this issue. If there is any further discussion, feel free to reopen this.

**Comment by Peachypie98** [comment]
It seems like this problem hasn't resolved for me. I'm still getting `TypeError: device(): argument 'index' (position 2) must be int, not str` error

All of the these methods didn't work.
*  `d3rlpy.load_learnable(MODEL_WEIGHT_PATH, 0)` 
*  `d3rlpy.load_learnable(MODEL_WEIGHT_PATH, '0')` 
*   `d3rlpy.load_learnable(MODEL_WEIGHT_PATH, 'cuda')` 

So, the workaround is to modify the `cuda` function code

![Image](https://github.com/user-attachments/assets/fc3babf3-3cb1-4fa6-94ff-111323dc129b)

I'm currently using d3rlpy version 2.7.0 and pytorch 2.6.0

**Comment by Morphlng** [comment]
@Peachypie98 Hi! Are you modifying the correct code? It seems like you are modifying "torch" instead of "d3rlpy". I'm using d3rlpy 2.5.0 and after the change of [d3rlpy/torch_utility.py](https://github.com/takuseno/d3rlpy/blob/0e8097b5fa77fcb85350bd039242d8af0b87504c/d3rlpy/torch_utility.py#L88), it works.

**Comment by Peachypie98** [comment]
Hello! 
Oh your right, I was modifying the wrong code. Thank you for your support!

Then perhaps, my d3rlpy 2.7.0 installation didnt actually apply the modified code which is a bit weird...

**Comment by takuseno** [comment]
Sorry, the fix is not released yet. I'll release the new version with the fix soon.

**Comment by takuseno** [comment]
I have just released the new package v2.8.0. If you do `pip install -U d3rlpy`, the issue has been resolved.

Release note is here: https://github.com/takuseno/d3rlpy/releases/tag/v2.8.0
